### ISSUE TITLE
Frightful Aspect shrinks aivu

### ISSUE THREAD

**Issue by TKDancer** [pheonix99/LevelableAivu#1]
seems frightful aspect is shrinking aivu instead of making her bigger(or keeping her large)  tested with the latest hotfix, went from large to medium, forcefully removing the buff makes he go back to large

might be worth testing to see if other size-altering effects cause this issue too

**Comment by pheonix99** [comment]
I'm pretty sure I know why this happens, still - Aivu's size-ups are implemented as size delta facts and frightful presence is a size delta fact and is overriding.

I can look into fixing if I can find a way to change base size directly.
