### ISSUE TITLE
Bug: Aivu reverted to Small

### ISSUE THREAD

**Issue by TKDancer** [pheonix99/LevelableAivu#8]
had a couple level ups ready for her and waited for the fix from a while ago that made it so her "mythic  class" could take more than 10 levels but with mod updated and game loaded again i gave her the level ups and she reset to small size, cant even force her size through toybox and looking through toybox she does have both size up feats, had to use old VA's scale override

**Comment by awaltersUPS** [comment]
Oh lovely.

Try respeccing and see if that fixes things if you would?

I can't get to it before this weekend, sorry.

**Comment by TKDancer** [comment]
i'll give that a try and i know it wasnt capped but i thought there was a bug you already fixed that prevented her from taking more than 10 levels in her mythic class(as in she didnt get to even see available classes at level 30) but thats neither here nor there ill try the long respec process and report back

**Comment by pheonix99** [comment]
Unable to replicate.
